### ISSUE TITLE
Idea: Let user turn off a specific message with a command!

### ISSUE THREAD

**Issue by Nesseley** [j0ach1mmall3/FreeAutoMessage#10]
First off all, this is a great plugin! 

Only thing I would like see added was for users to turn off one automessage after x times they have seen it.
Example:
Nesseley have played on the server for a while and has seen the message: "buy this and that on our website" 10 times.
Nesseley can now use a command you define in the config yourself to turn of the messages listed in (chat).

Config example: (chat)
http://pastebin.com/aRxSyV7D

I think this would make the plugin 100% complete!
Again, amazing plugin. Hope this get coded in!
- Nesseley

**Comment by j0ach1mmall3** [comment]
Probably not going to happen because then I need to store stuff for players etc which means a lot of work for a very little audience
