### ISSUE TITLE
BosBar Broadcast Bug

### ISSUE THREAD

**Issue by Danv97** [j0ach1mmall3/FreeAutoMessage#2]
Well I installed BosBarApi to be able to use the function of your plugin the problem is that I set 5 messages with random option set to false and cooldown of 600 = 30 seconds but the problem is that when I start the server it waits 30 seconds and skip to the second message without showing the first one until it start again since the first one and my first message is my welcome message so can you pls fix it

How it works:
- Starting Server
- After 30 secs
- " second broadcast"

How it should work:
- Starting Server
- " first broadcast
- after 30 secs
- " second broadcast

**Comment by j0ach1mmall3** [comment]
Well, set the welcome message as the first one? I'll look into it though

**Comment by j0ach1mmall3** [comment]
*second ond
