### ISSUE TITLE
json multiline not showing

### ISSUE THREAD

**Issue by boidy** [j0ach1mmall3/FreeAutoMessage#6]
Hi @j0ach1mmall3 I'm using this json from https://www.minecraftjson.com/ 

This is my finished code 

`{"text":"Rankup for FREE by just playing on the server!","color":"gold","bold":true},{"text":"Click ","color":"gray","bold":false},{"text":"HERE","color":"light_purple","bold":true,"clickEvent":{"action":"run_command","value":"ar check"}},{"text":" to check your play time for the next rank","color":"gray","bold":false}`

it should be showing like this:
![Image of correct display](http://i.imgur.com/G60r7WD.jpg)

but for some reason it is only showing the "**Rankup for FREE by just playing on the server!**" part of the message, the click event part and "to check your play time for the next rank" are missing completely

adding " **|** " between the  " **}, {** " makes it work but each part is on a new line, is it possible to show the entire json message on 1 -2  lines?

**Comment by j0ach1mmall3** [comment]
Mhmm well I'm just sending it like minecraft does, so standard minecraft 'rules' should apply...

**Comment by boidy** [comment]
-- Please reply above this line --


Hello,

We got your message! One of our customer support team will reply to
you as soon as possible.

Thanks!

**Comment by boidy** [comment]
I tried automessage from clip and had the same issue, but on his he says to add && between instances which works perfectly on his but not on Freeautomessage, I much prefer FAM due to the permissions and other message delivery methods, is it possible to workaround similar to clips method?

This is the code that shows perfectly on automessage plugin after swapping "," with "&&" I did it with fam, and got the first line of the second line to show but after that is blank still

announcements:
  default:
  - '{"text":"Rankup for FREE by just playing on the server!","color":"gold","bold":true}'
  - '{"text":"Click ","color":"gray","bold":false}&&{"text":"HERE","color":"light_purple","bold":true,"clickEvent":{"action":"run_command","value":"/ar check"}}&&{"text":" to check your play time for the next rank","color":"gray","bold":false}'

**Comment by j0ach1mmall3** [comment]
You'll probably have to use clip's fir that, sorry

**Comment by boidy** [comment]
-- Please reply above this line --


Hello,

We got your message! One of our customer support team will reply to
you as soon as possible.

Thanks!
