### ISSUE TITLE
Bar dissapears

### ISSUE THREAD

**Issue by DeveloperRic** [j0ach1mmall3/FreeAutoMessage#7]
Only I the owner can see the bar, and I cannot find any permission that may be causing this.

**Comment by j0ach1mmall3** [comment]
Make sure you're in the right world, have the permission, etc

**Comment by DeveloperRic** [comment]
Yes but what is the permission? I am opped so i can see it but others say they can't, I can't find the permission to see the bar, and I am in the right world.

**Comment by j0ach1mmall3** [comment]
It's right in the config...

**Comment by DeveloperRic** [comment]
Oh sorry about that I must have assumed it was a comment, thanks for the quick reply!
