### ISSUE TITLE
API

### ISSUE THREAD

**Issue by boomboompower** [j0ach1mmall3/FreeAutoMessage#8]
The ways you do things in the API is stupid. You are making a public API, then limiting it to only your plugin. For everyones sake, make the api need a _JavaPlugin_ variable, not your own main class.

**Comment by j0ach1mmall3** [comment]
Did you know you can actually retrieve the main class? Funny isn't it?
I'll show you the trick:
(Main) Bukkit.getPluginManager().getPlugin("FreeAutoMessage");
BOOM!

**Comment by csh** [comment]
Muggle method.
`JavaPlugin.getProvidingPlugin(ApiCrap.class)` is far more satisfying :(

**Comment by boomboompower** [comment]
@j0ach1mmall3 I know, but why should people have to do that, when you can make your code simply globally compatible.

**Comment by j0ach1mmall3** [comment]
Ya I'm lazy.
I don't get paid for this shit, and unless you do, I suggest you stop argueing.
Also, you're just being lazy aswell and can't be bothered to type a few extra words.

**Comment by boomboompower** [comment]
Yes I may be lazy, but notice
>  I'll even make a pr for you if I have to

Regardless of if you get paid or not, it's better practice and **is better** in the long term.

**Comment by j0ach1mmall3** [comment]
there
